version: "3"
services:
  app:
    build: ./
    env_file: ./.env
    restart: always
    command: npm run dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'